<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet
    version="3.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <!-- https://pl.wiktionary.org/wiki/Wikisłownik:Statystyka -->
  <xsl:variable
      name="allowed-languages"
      select="('język polski',
              'język angielski',
              'język niemiecki',
              'język słowacki',
              'język włoski',
              'język węgierski',
              'język ukraiński',
              'język bułgarski',
              'język rosyjski',
              'język francuski',
              'język czeski',
              'język hiszpański',
              'język baskijski',
              'język białoruski',
              'język szwedzki',
              'interlingua',
              'język łaciński',
              'esperanto',
              'język wilamowski',
              'język nowogrecki',
              'język portugalski',
              'język arabski',
              'język fiński',
              'jidysz',
              'język litewski',
              'język słoweński',
              'język turecki',
              'język kataloński',
              'język łotewski',
              'język duński',
              'język japoński',
              'język estoński',
              'język chorwacki',
              'język niderlandzki',
              'język islandzki',
              'język kaszubski',
              'język farerski',
              'język norweski (bokmål)',
              'język koreański',
              'język rumuński',
              'esperanto (morfem)',
              'język chiński standardowy',
              'język tajski',
              'język gruziński',
              'hindi',
              'język macedoński',
              'slovio',
              'język kazachski',
              'język ormiański',
              'język galicyjski',
              'język albański',
              'język wietnamski',
              'język asturyjski',
              'język norweski (nynorsk)',
              'język hebrajski',
              'język nowopruski',
              'język irlandzki',
              'język suahili',
              'język baszkirski',
              'język perski',
              'język luksemburski',
              'ido',
              'język azerski',
              'język starogrecki',
              'język serbski',
              'język indonezyjski',
              'język afrykanerski',
              'język karpatorusiński',
              'język turkmeński',
              'język szkocki gaelicki',
              'język telugu',
              'język dolnołużycki',
              'język tamilski',
              'język walijski',
              'sanskryt',
              'język górnołużycki',
              'język kurmandżi',
              'język bengalski',
              'język gudźarati',
              'język maltański',
              'język malgaski',
              'język tuvalu',
              'język uzbecki',
              'język tagalski',
              'język północnolapoński',
              'język grenlandzki',
              'język sycylijski',
              'volapük',
              'język hawajski',
              'język staroangielski',
              'język mongolski',
              'język adygejski',
              'język staro-cerkiewno-słowiański')"/>
</xsl:stylesheet>
