<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet
    version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:variable
      name="allowed-languages"
      select="('Português',
              'Galego',
              'Inglês',
              'Espanhol',
              'Japonês',
              'Francês',
              'Alemão',
              'Latim',
              'Asturiano',
              'Italiano',
              'Mirandês',
              'Esperanto',
              'Russo',
              'Chinês',
              'Catalão',
              'Islandês',
              'Polonês',
              'Finlandês',
              'Sueco',
              'Gaélico Escocês',
              'Língua Franca Nova',
              'Galego-Português Medieval',
              'Norueguês Bokmål',
              'Grego',
              'Árabe',
              'Dinamarquês',
              'Turco',
              'Tétum',
              'Romeno',
              'Basco',
              'Ido',
              'Curdo',
              'Húngaro',
              'Coreano',
              'Vietnamita',
              'Indonésio',
              'Occitano',
              'Galês',
              'Interlíngua',
              'Eslovaco',
              'Búlgaro',
              'Holandês/Neerlandês',
              'Checo/Tcheco')"/>
</xsl:stylesheet>
