<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet
    version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <!-- https://fr.wiktionary.org/wiki/Wiktionnaire:Statistiques -->
  <xsl:variable
      name="allowed-languages"
      select="('Français',
              'Italien',
              'Allemand',
              'Portugais',
              'Espagnol',
              'Russe',
              'Anglais',
              'Finnois',
              'Bulgare',
              'Latin',
              'Ukrainien',
              'Slovène',
              'Occitan',
              'Néerlandais',
              'Japonais',
              'Chinois',
              'Arabe',
              'Catalan',
              'Polonais',
              'Ancien français',
              'Vietnamien',
              'Indonésien',
              'Islandais',
              'Grec ancien',
              'Coréen',
              'Roumain',
              'Letton',
              'Ancien occitan',
              'Grec',
              'Same du Nord',
              'Tchèque',
              'Suédois',
              'Breton',
              'Basque',
              'Gallo',
              'Danois',
              'Malgache',
              'Estonien',
              'Afrikaans',
              'Sicilien',
              'Kazakh',
              'Turc',
              'Hongrois',
              'Gallois',
              'Luxembourgeois',
              'Slovaque',
              'Francoprovençal',
              'Papiamento',
              'Norvégien',
              'Norvégien (nynorsk)',
              'Norvégien (bokmål)',
              'Persan',
              'Bambara',
              'Lingala',
              'Songhaï koyraboro senni',
              'Frison',
              'Haoussa',
              'Gaulois',
              'Vieux slave',
              'Gaélique irlandais',
              'Okinawaïen',
              'Créole haïtien',
              'Inuktitut',
              'Moyen français',
              'Galicien',
              'Gallo-italique de Sicile',
              'Romanche',
              'Croate',
              'Azéri',
              'Tamoul',
              'Mongol',
              'Géorgien',
              'Albanais',
              'Picard',
              'Lituanien',
              'Tagalog',
              'Swahili',
              'Hébreu ancien',
              'Chleuh',
              'Malais',
              'Arménien',
              'Corse',
              'Hébreu',
              'Biélorusse',
              'Serbe',
              'Kurde',
              'Vieil anglais',
              'Kirghiz',
              'Bachkir',
              'Tatare',
              'Nahuatl classique',
              'Féroïen',
              'Népalais',
              'Hindi',
              'Tchouvache',
              'Lepcha',
              'Griko',
              'Gaélique écossais',
              'Cornique',
              'Tatar de Crimée',
              'Flamand occidental',
              'Palenquero',
              'Serbo-croate',
              'Turkmène',
              'Vieux haut allemand',
              'Asturien')"/>
</xsl:stylesheet>
