<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet
    version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <!-- https://de.wiktionary.org/wiki/Wiktionary:Statistik/Sprachenübersicht -->
  <xsl:variable
      name="allowed-languages"
      select="('Deutsch',
              'Englisch',
              'Latein',
              'Tschechisch',
              'Polnisch',
              'Italienisch',
              'Ukrainisch',
              'Französisch',
              'Katalanisch',
              'Esperanto',
              'Portugiesisch',
              'Schwedisch',
              'Spanisch',
              'Weißrussisch',
              'Russisch',
              'Mazedonisch',
              'Slowakisch',
              'Kroatisch',
              'Finnisch',
              'Okzitanisch',
              'Lettisch',
              'Altgriechisch',
              'Slowenisch',
              'Urdu',
              'Rumänisch',
              'Ungarisch',
              'Litauisch',
              'Albanisch',
              'Niederländisch',
              'Usbekisch',
              'Bulgarisch',
              'Dänisch',
              'Vietnamesisch',
              'Hausa')"/>
</xsl:stylesheet>
