<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet
    version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <!-- https://en.wiktionary.org/wiki/Wiktionary:Statistics -->
  <xsl:variable
      name="allowed-languages"
      select="('English',
              'German',
              'French',
              'Spanish',
              'Portuguese',
              'Italian',
              'Swedish',
              'Finnish',
              'Danish',
              'Norwegian',
              'Norwegian Bokmål',
              'Norwegian Nynorsk',
              'Russian',
              'Ukrainian',
              'Chinese',
              'Japanese',
              'Korean',
              'Hindi',
              'Bengali',
              'Indonesian',
              'Vietnamese',
              'Turkish',
              'Thai',
              'Arabic',
              'Hebrew',
              'Greek',
              'Polish',
              'Dutch',
              'Czech',
              'Icelandic',
              'Malay',
              'Persian',
              'Latin',
              'Old English',
              'Middle English',
              'Romanian',
              'Serbo-Croatian',
              'Macedonian',
              'Catalan',
              'Tagalog',
              'Hungarian',
              'Ancient Greek',
              'Irish',
              'Galician',
              'Bulgarian',
              'Sanskrit',
              'Tamil',
              'Armenian',
              'Welsh',
              'Georgian',
              'Cebuano',
              'Telugu',
              'Esperanto',
              'Albanian',
              'Azerbaijani',
              'Malayalam',
              'Scottish Gaelic',
              'Latvian',
              'Swahili',
              'Kazakh',
              'Slovak',
              'Burmese',
              'Lithuanian',
              'Estonian',
              'Uyghur',
              'Tibetan',
              'Mongolian',
              'Zhuang',
              'Manchu',
              'Khmer',
              'Lao',
              'Punjabi',
              'Urdu',
              'Pali',
              'Marathi',
              'Gujarati',
              'Kannada',
              'Odia',
              'Assamese',
              'Kashmiri',
              'Nepali',
              'Sindhi',
              'Konkani',
              'Maltese',
              'Yiddish',
              'Norman',
              'Navajo',
              'Ottoman Turkish',
              'Faroese',
              'Ingrian',
              'Ido',
              'Asturian',
              'Luxembourgish',
              'Central Bikol',
              'Slovene',
              'Pannonian Rusyn',
              'Old French',
              'Assyrian Neo-Aramaic',
              'Cornish',
              'Belarusian',
              'Afrikaans',
              'Old Armenian',
              'Haitian Creole',
              'Romansh',
              'Tajik',
              'Yakut',
              'Basque',
              'Kyrgyz',
              'Chechen',
              'Talysh',
              'Crimean Tatar',
              'Tatar',
              'Turkmen',
              'Tày',
              'Occitan',
              'Northern Kurdish',
              'West Circassian',
              'Ladin',
              'Old Irish',
              'Javanese',
              'Northern Sami',
              'Ahtna',
              'Khiamniungan Naga',
              'Scots',
              'Livonian',
              'Makasar',
              'Yoruba',
              'Middle French',
              'Classical Nahuatl',
              'Venetan',
              'Old Church Slavonic',
              'Plautdietsch',
              'Uzbek',
              'Old Czech',
              'Aromanian',
              'Cimbrian',
              'West Frisian',
              'Malagasy',
              'Lower Sorbian',
              'Lower Tanana',
              'Old High German',
              'Xhosa',
              'Votic',
              'Manx',
              'Zulu',
              'Sundanese',
              'Old Polish',
              'Sicilian',
              'Yola',
              'Bashkir',
              'Hawaiian',
              'Amharic',
              'Oromo',
              'Somali',
              'Tigrinya',
              'Afar',
              'Ge''ez',
              'Tarifit',
              'Gothic',
              'Old Norse',
              'Emilian',
              'South Levantine Arabic',
              'Central Kurdish',
              'Southern Kurdish',
              'Laz',
              'Ushojo',
              'Kashubian',
              'Northern Yukaghir',
              'Coptic',
              'Classical Syriac',
              'Franco-Provençal',
              'Shan',
              'Tangut',
              'Greenlandic',
              'Walloon',
              'Palula',
              'Māori',
              'Silesian',
              'Alemannic German',
              'Ladino',
              'Prakrit',
              'Quechua',
              'Tocharian B',
              'East Central German',
              'Hunsrik',
              'Pennsylvania German',
              'Unami',
              'Old Saxon',
              'Breton',
              'Low German',
              'Veps',
              'Cherokee',
              'Sumerian',
              'Akkadian',
              'Ye''kwana',
              'Middle Dutch',
              'Moroccan Arabic',
              'Aramaic',
              'Old Persian',
              'Hausa',
              'Friulian',
              'Ainu',
              'Bavarian',
              'Mokilese',
              'Khalaj',
              'Fula',
              'Tok Pisin',
              'Saterland Frisian',
              'Hiligaynon',
              'Hijazi Arabic',
              'Dhivehi',
              'Chichewa',
              'Old Javanese',
              'Sirenik',
              'Old Dutch',
              'Middle High German',
              'Old Japanese',
              'Old Korean',
              'Middle Korean',
              'Early Modern Korean',
              'Middle Low German',
              'Old Galician-Portuguese',
              'Old Spanish',
              'Old Swedish',
              'Egyptian Arabic',
              'North Levantine Arabic',
              'Gulf Arabic',
              'Old Georgian',
              'Central Nahuatl',
              'Southern Altai',
              'Northern Altai',
              'Jeju',
              'Ligurian',
              'Ojibwe',
              'North Frisian',
              'Woiwurrung',
              'Swazi',
              'Pashto',
              'Abkhaz',
              'Ilocano',
              'Old Tupi',
              'Chavacano',
              'Lingala',
              'Vilamovian',
              'Kumyk',
              'Akan',
              'Sranan Tongo',
              'Ubykh',
              'East Circassian',
              'Limburgish',
              'Kildin Sami',
              'Kapampangan',
              'Ternate',
              'Aragonese',
              'Phuthi',
              'Tausug',
              'Sinhalese',
              'Salar',
              'Udmurt',
              'Iban',
              'Kikuyu',
              'San Juan Quiahije Chatino',
              'Garo',
              'Kabuverdianu',
              'Dalmatian',
              'S''gaw Karen',
              'Romagnol',
              'Sardinian',
              'Northern Mansi',
              'Karelian')"/>
</xsl:stylesheet>
