<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet
    version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:variable
      name="allowed-languages"
      select="('English',
              'German',
              'French',
              'Spanish',
              'Portuguese',
              'Italian',
              'Swedish',
              'Finnish',
              'Danish',
              'Norwegian',
              'Norwegian Bokmål',
              'Norwegian Nynorsk',
              'Russian',
              'Ukrainian',
              'Chinese',
              'Japanese',
              'Korean',
              'Hindi',
              'Bengali',
              'Indonesian',
              'Vietnamese',
              'Turkish',
              'Thai',
              'Arabic',
              'Hebrew',
              'Greek',
              'Polish',
              'Dutch',
              'Czech',
              'Icelandic',
              'Malay',
              'Persian',
              'Latin',
              'Old English',
              'Middle English',
              'Romanian',
              'Serbo-Croatian',
              'Macedonian',
              'Catalan',
              'Tagalog',
              'Hungarian',
              'Ancient Greek',
              'Irish',
              'Galician',
              'Bulgarian',
              'Sanskrit',
              'Tamil',
              'Armenian',
              'Welsh',
              'Georgian',
              'Cebuano',
              'Telugu',
              'Esperanto',
              'Albanian',
              'Azerbaijani',
              'Malayalam',
              'Scottish Gaelic',
              'Latvian',
              'Swahili',
              'Kazakh',
              'Slovak',
              'Burmese',
              'Lithuanian',
              'Estonian',
              'Uyghur',
              'Tibetan',
              'Mongolian',
              'Zhuang',
              'Manchu')"/>
</xsl:stylesheet>
