name: build dictionaries

on:
  push:
    tags:
      - "*"
  schedule:
    - cron: "42 1 15 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        gloss_lang: ["en"]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: 3.14
      - run: python -m pip install .
      - run: dict ${{ matrix.gloss_lang }}
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
      - uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.gloss_lang }}
          if-no-files-found: error
          path: build/*.tar.zst

  release:
     needs: build
     runs-on: ubuntu-latest
     permissions:
       contents: write
     steps:
       - uses: actions/download-artifact@v8
       - name: Get date
         id: get-date
         run: |
           echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
       - uses: softprops/action-gh-release@v2
         with:
           tag_name: ${{ (github.event_name == 'push' && github.ref_name) || steps.get-date.outputs.date }}
           files: |
             **/*.tar.zst
